#ifndef SETTINGS_H
#define SETTINGS_H

#define JUMP_DISTANCE 5 
#define DEAD ' '
#define DEAD_FOREGROUND COLOR_BLACK
#define DEAD_BACKGROUND -1
#define ALIVE 'o'
#define ALIVE_FOREGROUND COLOR_GREEN
#define ALIVE_BACKGROUND -1
#define PADDING 10
#define DEFAULT_FPS 5.0
#define SPEED_CHANGE 0.1

#endif
